name: Run Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: docker
    container:
      image: node:21-bullseye

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run lint
